### ISSUE TITLE
Implement Spanish Deck/Deck Selection

### ISSUE THREAD

**Issue by vasquezt** [cs361fall2017/team34#25]
Currently the goal is to construct a new Spanish deck as well as the functionality required for the new rule set. In addition I will need to add the choice functionality to choose the type of deck.

**Comment by IamEricYou** [comment]
I will also look into it. I'm still confusing about the Spanish Deck.

**Comment by vasquezt** [comment]
Currently the deck selection and deck creation is both implemented. All that is left is the Joker rule for the Spanish Deck.
